import { Client, ClientStatus, Event, EventStatus } from "./types";

export const MOCK_CLIENTS: Client[] = [
  {
    id: "1",
    name: "Ana & Pedro",
    type: ClientStatus.Wedding,
    date: "02/12/2023",
    email: "ana.silva@gmail.com",
    phone: "(11) 99999-1234",
    instagram: "@ana_pedro_wedding",
    initials: ["A", "P"],
    colors: ["bg-blue-100", "bg-yellow-100"],
  },
  {
    id: "2",
    name: "Juliana Eventos",
    type: ClientStatus.Partner,
    date: "3 Eventos Ativos",
    email: "contato@jueventos.com.br",
    phone: "(21) 98888-5678",
    instagram: "@ju.cerimonial",
    initials: ["J"],
    colors: ["bg-purple-200"],
  },
  {
    id: "3",
    name: "Marcos & Livia",
    type: ClientStatus.Proposal,
    date: "Data a definir",
    email: "marcos.dev@email.com",
    phone: "(41) 91234-5678",
    instagram: "@marcoselivia",
    initials: ["M", "L"],
    colors: ["bg-green-100", "bg-pink-100"],
  },
  {
    id: "4",
    name: "Fazenda Vila Rica",
    type: ClientStatus.Partner,
    date: "5 Eventos Realizados",
    email: "eventos@vilarica.com.br",
    phone: "(19) 3333-4444",
    instagram: "@fazendavilarica",
    initials: ["V"],
    colors: ["bg-blue-200"],
  },
];

export const MOCK_EVENTS: Event[] = [
  {
    id: "1",
    title: "Julia & Marcos Wedding",
    clientName: "Julia Silva",
    date: "2023-12-02",
    day: "02",
    month: "DEC",
    weekday: "SATURDAY",
    location: "Fazenda Vila Rica",
    type: "Wedding",
    status: EventStatus.Booked,
    income: 5000,
    expense: 150,
    incomeItems: [
      { id: "inc1", date: "15/08/2023", description: "Sinal (50%)", category: "Payment via PIX", amount: 2500 },
      { id: "inc2", date: "01/12/2023", description: "Pagamento Final", category: "Bank Transfer", amount: 2500 },
    ],
    expenseItems: [
      { id: "exp1", date: "02/12/2023", description: "Uber (Ida e Volta)", category: "Transport", amount: 45.90 },
      { id: "exp2", date: "28/11/2023", description: "Tinta Acrílica & Verniz", category: "Materials", amount: 120.00 },
       { id: "exp3", date: "02/12/2023", description: "Jantar Equipe", category: "Meals", amount: 85.00 },
    ],
  },
  {
    id: "2",
    title: "Corporate Holiday Gala",
    clientName: "TechFlow Inc.",
    date: "2023-12-12",
    day: "12",
    month: "DEC",
    weekday: "TUESDAY",
    location: "Galeria Ponto",
    type: "Live Painting",
    status: EventStatus.Upcoming,
    income: 8500,
    expense: 0,
    incomeItems: [],
    expenseItems: [],
  },
  {
    id: "3",
    title: "Beach Painting Workshop",
    clientName: "Public Event",
    date: "2023-11-15",
    day: "15",
    month: "NOV",
    weekday: "WEDNESDAY",
    location: "Maresias",
    type: "Workshop",
    status: EventStatus.Completed,
    income: 1200,
    expense: 0,
    incomeItems: [],
    expenseItems: [],
  },
];

export const CHART_DATA = [
  { name: 'JUN', income: 4000, expense: 2500 },
  { name: 'JUL', income: 5500, expense: 3000 },
  { name: 'AGO', income: 4500, expense: 3500 },
  { name: 'SET', income: 7000, expense: 2000 },
  { name: 'OUT', income: 8500, expense: 4000 },
  { name: 'NOV', income: 6000, expense: 2500 },
];
